#!/bin/bash
####################################################################
####    Variables
baseurl_code="https://packages.microsoft.com/yumrepos/vscode";
gpg_key="https://packages.microsoft.com/keys/microsoft.asc";


echo "";
echo "-----------------------------------------------------------------------------------------------------------------------------------";
echo "---       Installing Google Chrome, Nvidia Driver";
echo "--------------------------------------------------------------";
#sudo dnf config-manager --set-enabled google-chrome rpmfusion-nonfree-nvidia-driver;
echo "-----------------------------------------------------------------------------------------------------------------------------------";
echo "";
echo "-----------------------------------------------------------------------------------------------------------------------------------";
echo "---	Installing Flatpathub Repo";
echo "--------------------------------------------------------------";
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo;
echo "--------------------------------------------------------------";
echo "";
echo "-----------------------------------------------------------------------------------------------------------------------------------";
echo "--->    Installing VSCode Repositori";
echo "--------------------------------------------------------------";
sudo rpm --import "$gpg_key";
printf "[code]
name=Visual Studio Code
baseurl=$baseurl_code
enabled=1
gpgcheck=1
gpgkey=$gpg_key
" > $HOME/vscode.repo;
sudo cp -v $HOME/vscode.repo  /etc/yum.repos.d/;
echo "-----------------------------------------------------------------------------------------------------------------------------------";
os-up;
echo "-----------------------------------------------------------------------------------------------------------------------------------";

